---
cluster.name: docker-cluster

# Bind to all interfaces because we don't know what IP address Docker will assign to us.
network.host: 0.0.0.0

# Note: discovery.type, plugins.security.disabled, and bootstrap.memory_lock 
# are set via environment variables in docker-compose to avoid duplication

