# Generated by Django 5.2.6 on 2025-09-18 07:54

import django.db.models.deletion
import modelcluster.contrib.taggit
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_customsite_site_ptr_alter_channel_created_at_and_more'),
        ('news', '0009_alter_articlepage_options_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepage',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AddField(
            model_name='articlepage',
            name='comment_count',
            field=models.PositiveIntegerField(default=0, help_text='文章评论总数', verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='favorite_count',
            field=models.PositiveIntegerField(default=0, help_text='文章收藏总数', verbose_name='收藏数'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='like_count',
            field=models.PositiveIntegerField(default=0, help_text='文章点赞总数', verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='reading_time',
            field=models.PositiveIntegerField(blank=True, help_text='预计阅读时长（分钟）', null=True, verbose_name='预计阅读时长'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='文章阅读次数', verbose_name='阅读量'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.RichTextField(help_text='✍️ 专业新闻编辑器 - 支持丰富的格式、媒体内容和表格功能', verbose_name='正文内容'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='channel',
            field=models.ForeignKey(blank=True, help_text='⚠️ 请只选择当前站点关联的频道（如上海站点请勿选择北京本地等其他站点专属频道）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='core.channel', verbose_name='频道'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='excerpt',
            field=models.TextField(blank=True, help_text='文章摘要，用于列表页展示和SEO', verbose_name='文章摘要'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='region',
            field=models.ForeignKey(blank=True, help_text='⚠️ 请只选择当前站点关联的地区', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='core.region', verbose_name='地区'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='news.ArticlePageTag', to='taggit.Tag', verbose_name='标签'),
        ),
    ]
