# Generated by Django 5.2.6 on 2025-09-19 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('news', '0010_alter_articlepage_options_articlepage_comment_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.customimage', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.customimage', verbose_name='专题封面图片'),
        ),
    ]
