# Generated by Django 5.2.6 on 2025-09-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_delete_collectionextension'),
        ('media', '0001_initial'),
        ('news', '0011_alter_articlepage_cover_alter_topic_cover_image'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='is_hero',
            field=models.BooleanField(default=False, help_text='是否在首页Hero轮播区域显示，需要配图', verbose_name='首页轮播'),
        ),
        migrations.AddIndex(
            model_name='articlepage',
            index=models.Index(fields=['is_hero', 'weight', 'publish_at'], name='art_hero_weight_pub'),
        ),
        migrations.AddIndex(
            model_name='articlepage',
            index=models.Index(fields=['is_hero', 'cover'], name='art_hero_cover'),
        ),
    ]
