# Generated by Django 5.2.6 on 2025-09-23 05:33

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_channeltemplate_remove_channel_channel_config_and_more'),
        ('news', '0012_add_is_hero_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='选择文章所属的分类（可多选）', related_name='articles', to='core.category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='topics',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='选择文章所属的专题（可多选）', related_name='articles', to='news.topic', verbose_name='专题'),
        ),
    ]
