# Generated by Django 5.2.6 on 2025-10-11 05:26

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_add_seo_fields'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='topic',
            name='news_topic_is_acti_a4143c_idx',
        ),
        migrations.RenameIndex(
            model_name='topic',
            new_name='news_topic_importa_36a6a4_idx',
            old_name='news_topic_import_status_idx',
        ),
        migrations.RenameIndex(
            model_name='topic',
            new_name='news_topic_status_0bab9a_idx',
            old_name='news_topic_status_active_idx',
        ),
        migrations.RenameIndex(
            model_name='topic',
            new_name='news_topic_priorit_bf376b_idx',
            old_name='news_topic_priority_created_idx',
        ),
        migrations.RenameIndex(
            model_name='topic',
            new_name='news_topic_is_brea_930474_idx',
            old_name='news_topic_breaking_featured_idx',
        ),
        migrations.RenameIndex(
            model_name='topic',
            new_name='news_topic_templat_b45880_idx',
            old_name='news_topic_template_active_idx',
        ),
        migrations.AlterField(
            model_name='topic',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='用于分类和模板映射的灵活标签系统', through='news.TopicTaggedItem', to='taggit.Tag', verbose_name='专题标签'),
        ),
    ]
