# Generated by Django 5.2.7 on 2025-11-07 08:09

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_add_channel_permissions'),
        ('news', '0016_remove_topic_news_topic_is_acti_a4143c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='为模板起一个易于识别的名称', max_length=200, verbose_name='模板名称')),
                ('template_type', models.CharField(choices=[('news', '📰 新闻稿'), ('interview', '🎤 专访'), ('review', '📝 评论'), ('feature', '✨ 特写'), ('announcement', '📢 公告'), ('tutorial', '📚 教程'), ('other', '📄 其他')], default='news', help_text='选择模板适用的文章类型', max_length=50, verbose_name='模板类型')),
                ('description', models.TextField(blank=True, help_text='说明此模板的用途和使用场景', verbose_name='模板描述')),
                ('title_template', models.CharField(blank=True, help_text='例如：【{类别}】{主题} - {副标题}', max_length=500, verbose_name='标题模板')),
                ('excerpt_template', models.TextField(blank=True, help_text='文章摘要的默认文本或结构', verbose_name='摘要模板')),
                ('body_template', wagtail.fields.RichTextField(blank=True, help_text='文章正文的默认结构，可包含占位符', verbose_name='正文模板')),
                ('default_tags', models.CharField(blank=True, help_text='使用此模板时自动添加的标签，用逗号分隔', max_length=500, verbose_name='默认标签')),
                ('default_author_name', models.CharField(blank=True, help_text='使用此模板时的默认作者名称', max_length=200, verbose_name='默认作者')),
                ('is_active', models.BooleanField(default=True, help_text='禁用后将不再显示在模板列表中', verbose_name='启用')),
                ('usage_count', models.IntegerField(default=0, help_text='记录此模板被使用的次数', verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('default_channel', models.ForeignKey(blank=True, help_text='使用此模板创建文章时的默认频道', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.channel', verbose_name='默认频道')),
            ],
            options={
                'verbose_name': '文章模板',
                'verbose_name_plural': '文章模板',
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
    ]
