# Generated by Django 5.2.6 on 2025-09-18 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('password_hash', models.CharField(max_length=128, verbose_name='密码哈希')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='昵称')),
                ('avatar', models.URLField(blank=True, verbose_name='头像')),
                ('bio', models.TextField(blank=True, verbose_name='个人简介')),
                ('reading_preferences', models.JSONField(default=dict, verbose_name='阅读偏好')),
                ('notification_settings', models.JSONField(default=dict, verbose_name='通知设置')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活状态')),
                ('is_verified', models.BooleanField(default=False, verbose_name='邮箱已验证')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后登录')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网站用户',
                'verbose_name_plural': '网站用户',
                'db_table': 'web_users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='所在地')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号码')),
                ('preferred_channels', models.JSONField(default=list, verbose_name='偏好频道')),
                ('preferred_categories', models.JSONField(default=list, verbose_name='偏好分类')),
                ('articles_read', models.IntegerField(default=0, verbose_name='阅读文章数')),
                ('comments_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('favorites_count', models.IntegerField(default=0, verbose_name='收藏数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='web_users.webuser')),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案',
                'db_table': 'web_user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=100, verbose_name='文章ID')),
                ('article_title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('article_slug', models.SlugField(verbose_name='文章链接')),
                ('article_channel', models.CharField(max_length=50, verbose_name='文章频道')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('parent_content', models.TextField(blank=True, verbose_name='父评论内容')),
                ('parent_author', models.CharField(blank=True, max_length=150, verbose_name='父评论作者')),
                ('status', models.CharField(choices=[('pending', '审核中'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('likes', models.IntegerField(default=0, verbose_name='点赞数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='web_users.usercomment', verbose_name='父评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='web_users.webuser')),
            ],
            options={
                'verbose_name': '用户评论',
                'verbose_name_plural': '用户评论',
                'db_table': 'web_user_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('article', '文章'), ('comment', '评论')], max_length=20, verbose_name='目标类型')),
                ('target_id', models.CharField(max_length=100, verbose_name='目标ID')),
                ('interaction_type', models.CharField(choices=[('like', '点赞'), ('dislike', '踩'), ('share', '分享'), ('view', '查看')], max_length=20, verbose_name='互动类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='web_users.webuser')),
            ],
            options={
                'verbose_name': '用户互动',
                'verbose_name_plural': '用户互动',
                'db_table': 'web_user_interactions',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'target_type', 'target_id', 'interaction_type')},
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=100, verbose_name='文章ID')),
                ('article_title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('article_slug', models.SlugField(verbose_name='文章链接')),
                ('article_channel', models.CharField(max_length=50, verbose_name='文章频道')),
                ('article_excerpt', models.TextField(blank=True, verbose_name='文章摘要')),
                ('article_image_url', models.URLField(blank=True, verbose_name='文章图片')),
                ('article_publish_time', models.DateTimeField(null=True, verbose_name='文章发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='web_users.webuser')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
                'db_table': 'web_user_favorites',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'article_id')},
            },
        ),
        migrations.CreateModel(
            name='ReadingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=100, verbose_name='文章ID')),
                ('article_title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('article_slug', models.SlugField(verbose_name='文章链接')),
                ('article_channel', models.CharField(max_length=50, verbose_name='文章频道')),
                ('read_time', models.DateTimeField(auto_now_add=True, verbose_name='阅读时间')),
                ('read_duration', models.IntegerField(default=0, verbose_name='阅读时长(秒)')),
                ('read_progress', models.IntegerField(default=0, verbose_name='阅读进度(%)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to='web_users.webuser')),
            ],
            options={
                'verbose_name': '阅读历史',
                'verbose_name_plural': '阅读历史',
                'db_table': 'web_reading_history',
                'ordering': ['-read_time'],
                'unique_together': {('user', 'article_id')},
            },
        ),
    ]
