# Generated by Django 5.2.6 on 2025-09-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='status',
            field=models.CharField(choices=[('pending', '审核中'), ('published', '已发布'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
