# Generated by Django 5.2.6 on 2025-09-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_users', '0002_alter_usercomment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinghistory',
            name='article_slug',
            field=models.CharField(max_length=200, verbose_name='文章链接'),
        ),
    ]
