# Generated by Django 5.2.6 on 2025-09-22 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_users', '0003_change_article_slug_to_charfield'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readinghistory',
            unique_together=set(),
        ),
    ]
