# Generated by Django 5.2.6 on 2025-10-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_users', '0004_remove_unique_constraint_reading_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='article_slug',
            field=models.SlugField(max_length=200, verbose_name='文章链接'),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='article_channel',
            field=models.CharField(max_length=100, verbose_name='文章频道'),
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='article_slug',
            field=models.SlugField(max_length=200, verbose_name='文章链接'),
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='article_channel',
            field=models.CharField(max_length=100, verbose_name='文章频道'),
        ),
    ]

