# Generated by Django 5.2.5 on 2025-08-21 07:27

import django.db.models.deletion
import modelcluster.fields
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIToolPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField(blank=True, verbose_name='工具描述')),
                ('tool_url', models.URLField(verbose_name='工具链接')),
                ('logo_url', models.URLField(blank=True, verbose_name='Logo链接')),
                ('category', models.CharField(choices=[('text-generation', '文字生成'), ('image-generation', '图像生成'), ('video-generation', '视频生成'), ('code-generation', '代码生成'), ('audio-generation', '音频生成'), ('data-analysis', '数据分析'), ('chatbot', '聊天机器人'), ('translation', '翻译'), ('productivity', '生产力'), ('research', '研究'), ('other', '其他')], default='other', max_length=50, verbose_name='工具分类')),
                ('pricing', models.CharField(choices=[('free', '免费'), ('freemium', '免费版'), ('paid', '付费'), ('enterprise', '企业版')], default='free', max_length=20, verbose_name='定价模式')),
                ('features', models.JSONField(default=list, verbose_name='功能特性')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='评分')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('is_hot', models.BooleanField(default=False, verbose_name='热门工具')),
                ('is_new', models.BooleanField(default=False, verbose_name='新工具')),
                ('channel_slug', models.SlugField(default='ai-tools', verbose_name='频道标识')),
                ('region', models.CharField(default='global', max_length=32, verbose_name='地区')),
                ('language', models.CharField(default='zh', max_length=8, verbose_name='语言')),
            ],
            options={
                'verbose_name': 'AI工具',
                'verbose_name_plural': 'AI工具',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AIToolPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='ai_tools.aitoolpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='aitoolpage',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='ai_tools.AIToolPageTag', to='taggit.Tag', verbose_name='标签'),
        ),
    ]
