# Generated by Django 5.2.5 on 2025-08-26 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='频道名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='频道标识')),
                ('description', models.TextField(blank=True, verbose_name='频道描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '频道',
                'verbose_name_plural': '频道',
                'db_table': 'core_channel',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='地区名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='地区标识')),
                ('description', models.TextField(blank=True, verbose_name='地区描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.region', verbose_name='父级地区')),
            ],
            options={
                'verbose_name': '地区',
                'verbose_name_plural': '地区',
                'db_table': 'core_region',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100, verbose_name='品牌名称')),
                ('brand_logo', models.URLField(blank=True, verbose_name='品牌Logo')),
                ('brand_description', models.TextField(blank=True, verbose_name='品牌描述')),
                ('seo_title', models.CharField(max_length=200, blank=True, verbose_name='SEO标题')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO描述')),
                ('seo_keywords', models.TextField(blank=True, verbose_name='SEO关键词')),
                ('google_analytics_id', models.CharField(max_length=50, blank=True, verbose_name='Google Analytics ID')),
                ('facebook_pixel_id', models.CharField(max_length=50, blank=True, verbose_name='Facebook Pixel ID')),
                ('default_language', models.CharField(max_length=10, default='zh', verbose_name='默认语言')),
                ('supported_languages', models.JSONField(default=list, verbose_name='支持的语言')),
                ('cache_timeout', models.IntegerField(default=300, verbose_name='缓存超时时间')),
                ('custom_config', models.JSONField(default=dict, verbose_name='自定义配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='wagtailcore.site', verbose_name='关联站点')),
            ],
            options={
                'verbose_name': '站点配置',
                'verbose_name_plural': '站点配置',
                'db_table': 'core_site_settings',
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='sites',
            field=models.ManyToManyField(related_name='channels', to='wagtailcore.site', verbose_name='关联站点'),
        ),
        migrations.AddField(
            model_name='region',
            name='sites',
            field=models.ManyToManyField(related_name='regions', to='wagtailcore.site', verbose_name='关联站点'),
        ),
    ]
