# Generated by Django 5.2.5 on 2025-08-27 07:26

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_missing_site_settings_fields'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='语言代码')),
                ('name', models.CharField(max_length=50, verbose_name='语言名称')),
                ('native_name', models.CharField(max_length=50, verbose_name='本地语言名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '语言',
                'verbose_name_plural': '语言',
                'db_table': 'core_language',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.RemoveField(
            model_name='channeltaggeditem',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='regiontaggeditem',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='facebook_pixel_id',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='seo_title',
        ),
        migrations.AlterField(
            model_name='channel',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='为频道添加标签，便于分类和搜索', through='core.ChannelTaggedItem', to='taggit.Tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='region',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='为地区添加标签，便于分类和搜索', through='core.RegionTaggedItem', to='taggit.Tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_logo',
            field=models.URLField(blank=True, verbose_name='品牌Logo URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='品牌名称'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cache_timeout',
            field=models.IntegerField(default=300, verbose_name='缓存超时时间(秒)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='custom_config',
            field=models.TextField(default='{}', help_text="JSON格式，例如：{'feature_flag': true, 'custom_setting': 'value'}", verbose_name='自定义配置'),
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='supported_languages',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='supported_languages',
            field=models.ManyToManyField(blank=True, help_text='选择此站点支持的语言', to='core.language', verbose_name='支持的语言'),
        ),
    ]
