# Generated by Django 5.2.5 on 2025-08-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_language_remove_channeltaggeditem_object_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomConfigItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('config_type', models.CharField(choices=[('boolean', '布尔值'), ('string', '字符串'), ('integer', '整数'), ('float', '浮点数'), ('json', 'JSON对象')], default='string', max_length=20, verbose_name='配置类型')),
                ('default_value', models.TextField(blank=True, verbose_name='默认值')),
                ('description', models.TextField(blank=True, verbose_name='配置描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '自定义配置项',
                'verbose_name_plural': '自定义配置项',
                'db_table': 'core_custom_config_item',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='custom_config',
            field=models.TextField(blank=True, default='{}', help_text="JSON格式，例如：{'feature_flag': true, 'custom_setting': 'value'}", verbose_name='自定义配置'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='所属区域'),
        ),
    ]
