# Generated by Django 5.2.5 on 2025-08-27 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_custom_config_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region', verbose_name='所属区域'),
        ),
    ]
