# Generated by Django 5.2.5 on 2025-08-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_update_region_to_foreign_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='custom_config',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='custom_config',
            field=models.ManyToManyField(blank=True, help_text='选择此站点启用的自定义配置项', to='core.customconfigitem', verbose_name='自定义配置'),
        ),
    ]
