# Generated by Django 5.2.5 on 2025-08-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_update_custom_config_to_many_to_many'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='格式名称')),
                ('format_string', models.CharField(max_length=50, unique=True, verbose_name='格式字符串')),
                ('example', models.CharField(max_length=50, verbose_name='示例')),
                ('description', models.TextField(blank=True, verbose_name='格式描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '日期格式',
                'verbose_name_plural': '日期格式',
                'db_table': 'core_date_format',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='字体名称')),
                ('css_value', models.CharField(max_length=200, verbose_name='CSS值')),
                ('category', models.CharField(max_length=50, verbose_name='字体分类')),
                ('description', models.TextField(blank=True, verbose_name='字体描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '字体',
                'verbose_name_plural': '字体',
                'db_table': 'core_font',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='主题名称')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='主题标识')),
                ('description', models.TextField(blank=True, verbose_name='主题描述')),
                ('preview_image', models.URLField(blank=True, verbose_name='预览图片URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '主题',
                'verbose_name_plural': '主题',
                'db_table': 'core_theme',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='时区名称')),
                ('value', models.CharField(max_length=50, unique=True, verbose_name='时区值')),
                ('offset', models.CharField(max_length=20, verbose_name='时区偏移')),
                ('description', models.TextField(blank=True, verbose_name='时区描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '时区',
                'verbose_name_plural': '时区',
                'db_table': 'core_timezone',
                'ordering': ['order', 'name'],
            },
        ),
    ]
