# Generated by Django 5.2.5 on 2025-08-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_theme_font_timezone_dateformat_models_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customconfigitem',
            name='config_type',
            field=models.CharField(default='string', max_length=20, verbose_name='配置类型'),
        ),
    ]
