# Generated by Django 5.2.5 on 2025-08-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_externalsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='brand_tokens',
            field=models.JSONField(default=dict, help_text="品牌设计令牌，JSON格式，如：{'primary': '#4F46E5', 'radius': '1rem'}", verbose_name='品牌设计令牌'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='layout_key',
            field=models.CharField(default='layout-localsite-grid', help_text='布局标识，如：layout-portal-classic, layout-localsite-grid', max_length=64, verbose_name='布局标识'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='modules',
            field=models.JSONField(default=dict, help_text="模块编排配置，JSON格式，如：{'home': ['hero','top-news'], 'sidebar': ['rank','ad']}", verbose_name='模块编排配置'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_key',
            field=models.CharField(default='localsite-default', help_text='主题标识，如：portal, localsite-default, localsite-shanghai', max_length=64, verbose_name='主题标识'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_keywords',
            field=models.TextField(blank=True, verbose_name='默认关键词'),
        ),
    ]
