# Generated by Django 5.2.5 on 2025-09-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sitesettings_brand_tokens_sitesettings_layout_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='customized',
            field=models.BooleanField(default=False, help_text='是否启用站点特定的覆盖组件，启用后将查找 overrides/{host}/ 目录', verbose_name='启用站点定制覆盖'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_version',
            field=models.CharField(default='1.0.0', help_text='语义化版本号，如：1.0.0, 2.1.3', max_length=16, verbose_name='主题版本'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='theme_key',
            field=models.CharField(default='localsite-default', help_text='主题标识，如：portal, localsite-default, magazine', max_length=64, verbose_name='主题标识'),
        ),
    ]
