# Generated by Django 5.2.5 on 2025-09-02 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_convert_localization_to_foreign_keys'),
        ('wagtailcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSite',
            fields=[
                ('site_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.site')),
                ('slug', models.SlugField(help_text='站点的唯一标识符，用于 URL 和代码中引用', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '站点',
                'verbose_name_plural': '站点',
            },
            bases=('wagtailcore.site',),
        ),
    ]
