# Generated by Django 5.2.6 on 2025-09-18 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_tag_model'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsite',
            name='site_ptr',
        ),
        migrations.AlterField(
            model_name='channel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='sites',
            field=models.ManyToManyField(blank=True, to='wagtailcore.site', verbose_name='关联站点'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='标识符'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='region',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='region',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='region',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.region', verbose_name='上级地区'),
        ),
        migrations.AlterField(
            model_name='region',
            name='sites',
            field=models.ManyToManyField(blank=True, to='wagtailcore.site', verbose_name='关联站点'),
        ),
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='标识符'),
        ),
        migrations.AlterField(
            model_name='region',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='api_rate_limit',
            field=models.IntegerField(default=1000, verbose_name='API速率限制'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_name',
            field=models.CharField(max_length=100, verbose_name='品牌名称'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='comments_enabled',
            field=models.BooleanField(default=False, verbose_name='评论功能'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='custom_config',
            field=models.ManyToManyField(blank=True, help_text='选择此站点启用的自定义配置项', to='core.customconfigitem', verbose_name='自定义配置项'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='lazy_loading',
            field=models.BooleanField(default=True, verbose_name='延迟加载'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='max_articles_per_page',
            field=models.IntegerField(default=20, verbose_name='每页文章数'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='recommendation',
            field=models.BooleanField(default=True, verbose_name='推荐系统'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CustomSite',
        ),
    ]
