# Generated by Django 5.2.6 on 2025-09-18 13:02
#
# 注意：这个迁移原本创建了 CollectionExtension 模型，
# 但该模型在后续迁移中被删除（0026-0030）。
# 为避免部署冲突，已将这些迁移合并为空操作。

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_customsite_site_ptr_alter_channel_created_at_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        # CollectionExtension 模型已在开发过程中被废弃
        # 原迁移 0025-0030 已合并为此空操作
    ]
