# Generated by Django 5.2.6 on 2025-09-18 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_customsite_site_ptr_alter_channel_created_at_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_slug', models.CharField(default='portal', help_text='关联的站点标识符', max_length=100, verbose_name='站点标识')),
                ('display_name', models.CharField(blank=True, help_text='用户友好的显示名称，支持中文等多语言', max_length=255, verbose_name='显示名称')),
                ('slug', models.SlugField(blank=True, help_text='URL友好的标识符，用于生成路径', max_length=100, verbose_name='路径标识')),
                ('description', models.TextField(blank=True, help_text='集合描述信息', verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活此集合', verbose_name='激活状态')),
                ('sort_order', models.IntegerField(default=0, help_text='排序顺序，数字越小越靠前', verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('collection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='wagtailcore.collection', verbose_name='集合')),
            ],
            options={
                'verbose_name': '集合扩展',
                'verbose_name_plural': '集合扩展',
                'ordering': ['sort_order', 'collection__name'],
                'indexes': [models.Index(fields=['site_slug'], name='core_collec_site_sl_fb1a4f_idx'), models.Index(fields=['slug'], name='core_collec_slug_723987_idx'), models.Index(fields=['is_active'], name='core_collec_is_acti_f916be_idx')],
            },
        ),
    ]
