# Generated by Django 5.2.6 on 2025-09-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_collection_extension'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, reverse_code=migrations.RunPython.noop),
    ]
