# Generated by Django 5.2.6 on 2025-09-18 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_cleanup_collectionextension_contenttype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectionExtension',
        ),
    ]
