# Generated by Django 5.2.6 on 2025-09-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_delete_collectionextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='homepage_order',
            field=models.IntegerField(default=0, help_text='在首页的显示顺序，数字越小越靠前', verbose_name='首页显示顺序'),
        ),
        migrations.AddField(
            model_name='channel',
            name='show_in_homepage',
            field=models.BooleanField(default=True, help_text='是否在首页显示频道条带', verbose_name='首页显示'),
        ),
    ]
