# Generated by Django 5.2.6 on 2025-09-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_homepage_display_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_config',
            field=models.JSONField(blank=True, default=dict, help_text='频道的个性化配置选项', verbose_name='频道配置'),
        ),
        migrations.AddField(
            model_name='channel',
            name='template_type',
            field=models.CharField(choices=[('shared', '共享模板 - 标准化展示'), ('independent', '独立模板 - 基础个性化'), ('magazine', '杂志模板 - 深度内容'), ('news_hub', '新闻中心模板 - 实时更新'), ('topic_focused', '专题模板 - 主题聚焦'), ('multimedia', '多媒体模板 - 富媒体展示'), ('custom', '完全自定义 - 高级配置')], default='independent', help_text='选择频道的展示模板类型', max_length=20, verbose_name='模板类型'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='has_own_template',
            field=models.BooleanField(default=True, help_text='此字段已废弃，请使用模板类型字段', verbose_name='是否独立模板 (已废弃)'),
        ),
    ]
