# Generated by Django 5.2.6 on 2025-09-22 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_add_template_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='has_own_template',
        ),
    ]
