# Generated by Django 5.2.6 on 2025-09-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_deprecated_has_own_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='template_type',
            field=models.CharField(choices=[('shared', '共享模板 - 标准化展示'), ('independent', '独立模板 - 基础个性化'), ('magazine', '杂志模板 - 深度内容'), ('news_hub', '新闻中心模板 - 实时更新'), ('topic_focused', '专题模板 - 主题聚焦'), ('multimedia', '多媒体模板 - 富媒体展示'), ('social_news', '社会新闻模板 - 人文关怀'), ('custom', '完全自定义 - 高级配置')], default='independent', help_text='选择频道的展示模板类型', max_length=20, verbose_name='模板类型'),
        ),
    ]
