# Generated by Django 5.2.6 on 2025-09-22 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_add_social_news_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如：社会新闻模板', max_length=100, verbose_name='模板名称')),
                ('slug', models.SlugField(help_text='如：social，用于匹配频道slug', unique=True, verbose_name='模板标识')),
                ('file_name', models.CharField(help_text='如：SocialTemplate.tsx', max_length=100, verbose_name='模板文件名')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否为默认模板')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '频道模板',
                'verbose_name_plural': '频道模板',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='channel',
            name='channel_config',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='template_type',
        ),
        migrations.AddField(
            model_name='channel',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.channeltemplate', verbose_name='频道模板'),
        ),
    ]
