# Generated by Django 5.2.5 on 2025-08-21 07:27

import django.db.models.deletion
import modelcluster.fields
import taggit.managers
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AINewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(blank=True, verbose_name='摘要')),
                ('body', wagtail.fields.RichTextField(verbose_name='正文')),
                ('channel_slug', models.SlugField(default='ai-news', verbose_name='频道标识')),
                ('topic_slug', models.SlugField(blank=True, default='', verbose_name='话题标识')),
                ('author_name', models.CharField(blank=True, default='', max_length=64, verbose_name='作者')),
                ('has_video', models.BooleanField(default=False, verbose_name='包含视频')),
                ('region', models.CharField(default='global', max_length=32, verbose_name='地区')),
                ('language', models.CharField(default='zh', max_length=8, verbose_name='语言')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='来源')),
                ('source_url', models.URLField(blank=True, verbose_name='来源链接')),
                ('image_url', models.URLField(blank=True, verbose_name='配图链接')),
                ('category', models.CharField(choices=[('technology', '技术突破'), ('product', '产品发布'), ('investment', '投资融资'), ('research', '研究突破'), ('policy', '政策法规'), ('industry', '行业动态'), ('startup', '创业公司'), ('academic', '学术研究')], default='technology', max_length=50, verbose_name='资讯分类')),
                ('is_hot', models.BooleanField(default=False, verbose_name='热门资讯')),
                ('is_top', models.BooleanField(default=False, verbose_name='置顶资讯')),
                ('read_count', models.IntegerField(default=0, verbose_name='阅读次数')),
            ],
            options={
                'verbose_name': 'AI资讯',
                'verbose_name_plural': 'AI资讯',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AINewsPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='ai_news.ainewspage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ainewspage',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='ai_news.AINewsPageTag', to='taggit.Tag', verbose_name='标签'),
        ),
    ]
