# Generated by Django 5.2.5 on 2025-08-21 07:27

import django.db.models.deletion
import modelcluster.fields
import taggit.managers
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITutorialPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(blank=True, verbose_name='教程简介')),
                ('body', wagtail.fields.RichTextField(verbose_name='教程内容')),
                ('difficulty', models.CharField(choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级')], default='beginner', max_length=20, verbose_name='难度等级')),
                ('duration', models.CharField(blank=True, max_length=50, verbose_name='预计时长')),
                ('author_name', models.CharField(blank=True, default='', max_length=64, verbose_name='作者')),
                ('category', models.CharField(choices=[('chatbot', '聊天机器人'), ('image-generation', '图像生成'), ('video-generation', '视频生成'), ('code-generation', '代码生成'), ('ai-fundamentals', 'AI基础'), ('data-analysis', '数据分析'), ('ai-ethics', 'AI伦理'), ('ai-business', 'AI商业'), ('nlp', '自然语言处理'), ('computer-vision', '计算机视觉'), ('machine-learning', '机器学习')], default='ai-fundamentals', max_length=50, verbose_name='教程分类')),
                ('is_hot', models.BooleanField(default=False, verbose_name='热门教程')),
                ('is_free', models.BooleanField(default=True, verbose_name='免费教程')),
                ('student_count', models.IntegerField(default=0, verbose_name='学习人数')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='评分')),
                ('channel_slug', models.SlugField(default='ai-tutorials', verbose_name='频道标识')),
                ('region', models.CharField(default='global', max_length=32, verbose_name='地区')),
                ('language', models.CharField(default='zh', max_length=8, verbose_name='语言')),
            ],
            options={
                'verbose_name': 'AI教程',
                'verbose_name_plural': 'AI教程',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AITutorialPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='ai_tutorials.aitutorialpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='aitutorialpage',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='ai_tutorials.AITutorialPageTag', to='taggit.Tag', verbose_name='标签'),
        ),
    ]
