analytics:
  baidu_analytics_id: ''
  export_enabled: true
  google_analytics_id: ''
  retention_days: 90
  track_performance: true
  track_user_behavior: true
content:
  allow_aggregate: true
  auto_publish: false
  content_approval_required: false
  content_retention_days: 365
  date_format: '%Y-%m-%d'
  default_language: zh
  supported_languages:
  - zh
  - en
  timezone: Asia/Shanghai
created_at: '2025-08-27T05:17:53.041831+00:00'
custom:
  debug_mode: true
  enable_hot_reload: true
  log_level: DEBUG
  region: ''
  region_order: 0
  show_debug_info: true
description: 本地开发环境 站点配置
features:
  analytics_enabled: true
  api_access: true
  comments_enabled: false
  content_moderation: false
  recommendation: true
  rss_feed: true
  search_enabled: true
  sitemap: true
  social_login: false
  user_registration: true
performance:
  api_rate_limit: 1000
  cache_timeout: 300
  cdn_enabled: false
  image_compression: true
  lazy_loading: true
  max_articles_per_page: 20
  max_search_results: 100
seo:
  default_description: ''
  default_keywords: ''
  default_title: 本地开发环境
  robots_txt_enabled: true
  sitemap: true
  social_meta_tags: true
  structured_data: true
site_id: localhost
site_name: 本地开发环境
site_url: http://localhost
ui:
  dark_mode_enabled: true
  favicon_url: ''
  font_family: Inter, sans-serif
  logo_url: ''
  primary_color: '#3B82F6'
  secondary_color: '#6B7280'
  show_breadcrumbs: true
  show_reading_time: true
  theme: modern
updated_at: '2025-08-27T13:24:14.088611'
version: '2.0'
