analytics:
  baidu_analytics_id: BA-SITEA-001
  export_enabled: false
  google_analytics_id: GA-SITEA-001
  retention_days: 180
  track_performance: true
  track_user_behavior: true
content:
  allow_aggregate: true
  auto_publish: false
  content_approval_required: true
  content_retention_days: 730
  date_format: '%Y年%m月%d日'
  default_language: zh
  supported_languages:
  - zh
  - en
  timezone: Asia/Shanghai
created_at: '2025-08-25T00:00:00'
custom:
  content_categories:
  - AI技术
  - 机器学习
  - 深度学习
  - 自然语言处理
  - 计算机视觉
  content_style: 深度技术分析
  debug_mode: false
  enable_hot_reload: false
  log_level: INFO
  show_debug_info: false
  target_audience: 技术专业人士
description: 专注于AI技术和科技创新的专业站点
features:
  ai_recommendation: true
  analytics_enabled: true
  api_access: true
  comments_enabled: true
  content_moderation: true
  recommendation: true
  rss_feed: true
  search_enabled: true
  sitemap: true
  social_login: true
  user_registration: true
performance:
  api_rate_limit: 500
  cache_timeout: 600
  cdn_enabled: true
  image_compression: true
  lazy_loading: true
  max_articles_per_page: 15
  max_search_results: 50
seo:
  default_description: ''
  default_keywords: ''
  default_title: ''
  meta_description: 探索AI技术前沿，分享最新科技资讯和深度分析
  meta_keywords: AI技术,人工智能,机器学习,科技资讯,技术分析
  meta_title: AI科技前沿 | Site A
  robots_txt_enabled: true
  sitemap: true
  sitemap_enabled: true
  social_meta_tags: true
  structured_data: true
site_id: site-a.local
site_name: AI科技站点
site_url: https://site-a.local
ui:
  dark_mode_enabled: true
  favicon_url: /static/images/site-a-favicon.ico
  font_family: Roboto, sans-serif
  logo_url: /static/images/site-a-logo.png
  primary_color: '#0EA5E9'
  secondary_color: '#64748B'
  show_breadcrumbs: true
  show_reading_time: true
  theme: tech
updated_at: '2025-08-27T13:24:14.054552'
version: '1.0'
